runtime: nodejs16

env_variables:
  MONGO_URI: "mongodb+srv://shamone:huWzzjo5Cug4P96l@cluster0.rdj2r.mongodb.net/ECR14?retryWrites=true&w=majority"
  CLIENT_SECRET: "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"
  REFRESH_TOKEN: "1//048Ks6mJ6YqtMCgYIARAAGAQSNwF-L9Ir_H4gr2yZMQEmCmnoqilrrboCozEe5GgDb_HrkCh6CbnzyzYoUaSGDsru9POTpXkZhq8"
  JWT_SECRET: "aegaegaevaeth2fawo;nvaer028470249-5jo;anvh;[a49t;a/ga3;ghb'g3"
  CLIENT_ID: "895699940676-5dbevjl83o11k1a3flvqrh0eak9oqs9t.apps.googleusercontent.com"
  BASE_URL: "ecr14.org"

handlers:
  - url: /home
    secure: always
    static_files: client/build/index.html
    upload: client/build/index.html
  - url: /login
    secure: always
    static_files: client/build/index.html
    upload: client/build/index.html
  - url: /register
    secure: always
    static_files: client/build/index.html
    upload: client/build/index.html
  - url: /survey
    secure: always
    static_files: client/build/index.html
    upload: client/build/index.html
  - url: /vote
    secure: always
    static_files: client/build/index.html
    upload: client/build/index.html
  - url: /vote/vote-now
    secure: always
    static_files: client/build/index.html
    upload: client/build/index.html
  - url: /construction
    secure: always
    static_files: client/build/index.html
    upload: client/build/index.html
  - url: /settings
    secure: always
    static_files: client/build/index.html
    upload: client/build/index.html
  - url: /verify/(.*)/verify/(.*)
    static_files: client/build/index.html
    upload: client/build/index.html
  - url: /static
    static_dir: client/build/static
  - url: /(.*)
    secure: always
    redirect_http_response_code: 301
    script: auto